name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: build
        run: |
          cd seronc
          make
          # ./seronc
          # ./seronc ./test/main.srn
          # ./test/main
